nama = input("Nama kamu adalah: ")
kelas = input("Kelas berapa: ")
umur = input("Umur kamu berapa: ")
hobi = input("Hobi kamu adalah: ")
makanan = input("Makanan kesukaan kamu apa: ")
film = input("Film Fav kamu adalah: ")
sekolah = input("Sekolah kamu dimana: ")
jurusan = input("Jurusan kamu adalah: ")
mapel = input("Mapel Fav kamu adalah: ")
game = input("Game Fav kamu adalah: ")
print("Perkenalkan nama saya adalah",nama,"Saya berada di kelas",kelas,"Saya mengambil jurusan",jurusan,"Saya bersekolah di",sekolah,"Hobi saya adalah",hobi,"Makanan Kesukaan saya adalah",makanan,"Film kesukaan saya adalah",film,"Mapel kesukaan saya adalah",mapel,"Game Kesukaan saya adalah",game)